In [2]:
import numpy as np
b=np.random.randint(15,50,(2,3))
b

array([[45, 16, 31],
       [47, 18, 44]])

In [3]:
np.std([[1,2],[3,4]])

1.118033988749895

In [4]:
np.var([[3,2],[2,1]])

0.5

In [5]:
np.prod(b)

830839680

In [6]:
np.prod([[1,2],[5,6]])

60

In [7]:
a=np.arange(5,15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.mean(a)

9.5

In [9]:
b=np.random.randint(0,50,11)
b

array([ 7, 15, 36, 17, 35, 46, 40, 11, 11, 24, 24])

In [10]:
np.median(b)

24.0

In [11]:
np.percentile(b,100)

46.0

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
big_array=np.arange(10000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1.09 ms ± 149 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
14.4 µs ± 720 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [32]:
b=np.random.randint(0,10,(3,3))
np.any(b)

True

In [34]:
b

array([[1, 9, 1],
       [3, 8, 0],
       [8, 1, 0]])

In [1]:
import numpy as np
a=np.arange(1,10)
np.sum(a)

45

In [2]:
np.min(a)

1

In [3]:
np.max(a)

9

In [4]:
b=np.random.randint(2,8,(3,3))
b

array([[6, 3, 5],
       [5, 4, 5],
       [6, 3, 4]])

In [5]:
b.sum(),b.max(),b.min()

(41, 6, 3)

In [6]:
b.sum(axis=1),b.min(axis=0),b.max(axis=0)

(array([14, 14, 13]), array([5, 3, 4]), array([6, 4, 5]))

In [7]:
np.prod([[6,5],[1,5]])

150

In [8]:
c=np.array([[1,4,7,10],[2,5,8,11]])
np.std(c)

3.391164991562634

In [9]:
rng=np.random.default_rng(seed=1701)
x=rng.integers(10,size=(3,3))
x

array([[9, 4, 0],
       [3, 8, 6],
       [3, 1, 3]], dtype=int64)

In [10]:
np.count_nonzero(x<6)

6

In [11]:
np.count_nonzero(x)

8

In [12]:
a=np.array([[9, np.nan, 0],
       [3, 8, 6],
       [3, 1, 3]])
a

array([[ 9., nan,  0.],
       [ 3.,  8.,  6.],
       [ 3.,  1.,  3.]])

In [13]:
np.count_nonzero(x<6)

6

In [14]:
np.count_nonzero(x)

8

In [15]:
import numpy as np
x=np.array([[9, 7, 0],
       [3, 8, 6],
       [3, 1, 3]])
x

array([[9, 7, 0],
       [3, 8, 6],
       [3, 1, 3]])

In [16]:
x[x<=3] #Mask

array([0, 3, 3, 1, 3])

In [17]:
y=x[x>3]
y

array([9, 7, 8, 6])

In [18]:
y.reshape(2,2)

array([[9, 7],
       [8, 6]])

In [19]:
bool(42 & 0)


False

In [20]:
bool(67 or 0)

True

In [21]:
bool(0 | 0)

False

In [22]:
bin(7)

'0b111'

In [23]:
bin(4 and 6)

'0b110'

In [24]:
a=np.array([1,0,1,0,1,0,1],dtype=bool)
b=np.array([1,1,0,1,1,0,0],dtype=bool)
a | b

array([ True,  True,  True,  True,  True, False,  True])

In [25]:
x=np.arange(10)
(x>4) & (x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [26]:
rng=np.random.default_rng(seed=1701)
x=rng.integers(100,size=10)
x

array([90, 40,  9, 30, 80, 67, 39, 15, 33, 79], dtype=int64)

In [27]:
a=[x[3],x[7],x[2]]
a

[30, 15, 9]

In [28]:
type(a)

list

In [29]:
ind=[3,7,4]
x[ind] #Fancy Indexing

array([30, 15, 80], dtype=int64)

In [30]:
ind=np.array([[3,7],[4,5]])
x[ind]

array([[30, 15],
       [80, 67]], dtype=int64)

In [31]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
row=np.array([0,1,2])
col=np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [33]:
x[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [34]:
x[row[:,np.newaxis]]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [35]:
row[:,np.newaxis]*col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

In [36]:
[row[:,np.newaxis]]


[array([[0],
        [1],
        [2]])]

In [37]:
a=np.array([[[10,20,20,40],[1,2,3,4],[5,6,7,10],[15,16,17,19]],[[55,56,57,58],[41,42,43,44],[31,32,33,34],[21,22,23,24]]])
a

array([[[10, 20, 20, 40],
        [ 1,  2,  3,  4],
        [ 5,  6,  7, 10],
        [15, 16, 17, 19]],

       [[55, 56, 57, 58],
        [41, 42, 43, 44],
        [31, 32, 33, 34],
        [21, 22, 23, 24]]])

In [38]:

x=a[0,[0,1,2,3],[0,1,2,3]]

y=a[1,[0,1,2,3],[0,1,2,3]]
print(x,y)

[10  2  7 19] [55 42 33 24]
