In [1]:
import numpy as np
array=np.array([1.2,5.3,4.9,1.32,7.9])
print(array)

[1.2  5.3  4.9  1.32 7.9 ]


In [2]:
array.dtype

dtype('float64')

In [3]:
array.argmax()

4

In [4]:
array.argmin()

0

In [5]:
array.min()

1.2

In [6]:
array.max()

7.9

In [7]:
array.argsort()

array([0, 3, 2, 1, 4], dtype=int64)

In [8]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.arange(0,10,2,int)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3,int)

array([0, 0, 0])

In [11]:
np.zeros((4,4,2),dtype=int,)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [12]:
np.ones(4,int)

array([1, 1, 1, 1])

In [13]:
np.ones((4,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [14]:
np.ones((5,2,3),int)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [15]:
np.linspace(2.0,3.0,5,endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [17]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
a=np.random.rand(3,2,1)
a

array([[[0.35383783],
        [0.99793235]],

       [[0.45015136],
        [0.20165908]],

       [[0.62253884],
        [0.87009018]]])

In [12]:
np.random.rand(4,4,1)

array([[[0.53306019],
        [0.46487548],
        [0.57505879],
        [0.02711948]],

       [[0.58457668],
        [0.19599432],
        [0.16574931],
        [0.26553765]],

       [[0.29009291],
        [0.72759516],
        [0.17760623],
        [0.31143812]],

       [[0.04952832],
        [0.10488671],
        [0.9676202 ],
        [0.58619557]]])

In [14]:
3 + 2.5 * np.random.randn(2, 4)

array([[ 2.03511769,  4.7148459 ,  1.56521631,  2.41318465],
       [-0.82719876,  6.58552839,  7.67208505,  5.1631415 ]])

In [64]:
np.random.randint(1,100,5)

array([84, 88, 18, 19, 38])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr=np.arange(25)
arr=np.random.randint(0,50,25)
arr

array([12, 27, 39, 26, 25,  6, 45, 12, 49,  2, 11, 21,  5,  0, 12, 21, 48,
       41, 15, 26, 19, 33, 39, 15, 36])

In [89]:
y=arr.reshape(5,5)
y

array([[46, 23, 25, 24, 44],
       [40, 28, 14, 44,  0],
       [24,  6,  8, 23,  0],
       [43,  7, 23, 10, 16],
       [ 7, 34, 34, 32,  4]])

In [82]:
np.argmax(arr)

0

In [83]:
np.argmin(arr)

9

In [84]:
np.max(arr)

46

In [85]:
np.min(arr)

0

In [90]:
y.shape

(5, 5)

In [92]:
y.dtype

dtype('int32')

In [94]:
a.dtype

dtype('float64')

In [28]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
a+b

array([ 2,  4,  6,  8, 10, 12])

In [36]:
np.shape(arr)

(25,)

In [38]:
a=np.array([1,2,3,4,5],int)
a

array([1, 2, 3, 4, 5])

In [43]:
np.shape(a)

(5,)

In [41]:
arr

array([12, 27, 39, 26, 25,  6, 45, 12, 49,  2, 11, 21,  5,  0, 12, 21, 48,
       41, 15, 26, 19, 33, 39, 15, 36])

In [42]:
arr[3]

26

In [44]:
arr[:6:2]

array([12, 39, 25])

In [45]:
arr[1:4]=50
arr

array([12, 50, 50, 50, 25,  6, 45, 12, 49,  2, 11, 21,  5,  0, 12, 21, 48,
       41, 15, 26, 19, 33, 39, 15, 36])

In [52]:
arr_2d = np.array(([245,510,379],[550,256,245],[780,278,398]))
arr_2d

array([[245, 510, 379],
       [550, 256, 245],
       [780, 278, 398]])

In [53]:
arr_2d[1][0]

550

In [54]:
arr_2d[2]

array([780, 278, 398])

In [55]:
arr_2d[:2]

array([[245, 510, 379],
       [550, 256, 245]])

In [56]:
arr = np.arange(2,7)
arr

array([2, 3, 4, 5, 6])

In [60]:
a=arr<4
a

array([ True,  True, False, False, False])

In [64]:
arr[a]

array([2, 3])

In [79]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [80]:
np.shape(a)

(4, 3)

In [82]:
a.shape

(4, 3)

In [86]:
a=a.reshape(3,4)
a.shape

(3, 4)

In [104]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]],[[1,3,5],[2,4,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[1, 3, 5],
        [2, 4, 6]]])

In [105]:
arr3[1][1]

array([1, 2, 3])

In [103]:
a[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [96]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 3, 4]])

In [107]:
arr3[1:2,:1,1:]

array([[[8, 9]]])